SELECT DISTINCT Book_Year FROM BOOK ORDER BY Book_Year;

SELECT DISTINCT Book_Subject FROM BOOK ORDER BY Book_Subject;

SELECT DISTINCT Book_Num, Book_Title, Book_Cost FROM BOOK 
WHERE Book_Cost = 59.95
ORDER BY Book_Num;

SELECT PAT_ID, PAT_FNAME, PAT_LNAME FROM PATRON
WHERE UPPER(PAT_TYPE) = "STUDENT"
ORDER BY PAT_ID;

SELECT * FROM PATRON
WHERE LEFT(PAT_LNAME,1) = 'C'
ORDER BY PAT_ID;

SELECT AU_ID, AU_FNAME, AU_LNAME FROM AUTHOR
WHERE AU_BIRTHYEAR IS NULL
ORDER BY AU_ID;

SELECT COUNT(*) AS 'Number of Books' FROM BOOK;

SELECT COUNT(DISTINCT Book_Subject) AS 'Number of Subjects' FROM BOOK;

SELECT * 
FROM BOOK AS A
LEFT JOIN CHECKOUT AS B ON A.BOOK_NUM = B.BOOK_NUM
WHERE CHECK_OUT_DATE IS NULL;

SELECT COUNT(DISTINCT A.BOOK_NUM)
FROM BOOK AS A
LEFT JOIN CHECKOUT AS B ON A.BOOK_NUM = B.BOOK_NUM
WHERE CHECK_IN_DATE IS NOT NULL OR CHECK_NUM IS NULL;

SELECT MAX(BOOK_COST) FROM BOOK;

SELECT MIN(BOOK_COST) FROM BOOK;

SELECT COUNT(DISTINCT(A.PAT_ID)) AS 'DIFFERENT PATRONS'
FROM PATRON AS A
JOIN CHECKOUT AS B ON A.PAT_ID=B.PAT_ID
JOIN BOOK AS C ON B.BOOK_NUM=C.BOOK_NUM;

SELECT A.AU_ID, COUNT(B.BOOK_NUM) AS 'Books Written'
FROM AUTHOR AS A
JOIN WRITES AS B ON A.AU_ID = B.AU_ID
JOIN BOOK AS C ON B.BOOK_NUM=C.BOOK_NUM
GROUP BY AU_ID
ORDER BY COUNT(B.BOOK_NUM) DESC, A.AU_ID;

SELECT A.PAT_ID, A.PAT_FNAME, PAT_LNAME
FROM PATRON AS A
LEFT JOIN CHECKOUT AS B ON A.PAT_ID = B.PAT_ID
WHERE CHECK_NUM IS NULL
ORDER BY A.PAT_LNAME, A.PAT_FNAME;

(SELECT A.EMP_FNAME, A.EMP_LNAME
FROM LGEMPLOYEE AS A
JOIN LGDEPARTMENT AS B ON A.DEPT_NUM = B.DEPT_NUM
WHERE DEPT_NAME = 'ACCOUNTING')
INTERSECT
(SELECT C.EMP_FNAME, C.EMP_LNAME
FROM LGEMPLOYEE AS C
JOIN LGDEPARTMENT AS D ON C.DEPT_NUM = D.DEPT_NUM
WHERE DEPT_NAME = 'MARKETING');

SELECT B.EMP_FNAME, B.EMP_LNAME
FROM LGCUSTOMER AS A
JOIN LGEMPLOYEE AS B ON A.CUST_FNAME = B.EMP_FNAME AND A.CUST_LNAME = B.EMP_LNAME;

SELECT * 
FROM LGDEPARTMENT;